name: Incentive Pictures
favicon: null
layout_spectrum: 0.3127290129195899
typography_spectrum: 0.66664
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
title: Incentive Pictures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252528'
    - '#5d6671'
    - '#feffff'
    - '#8895a7'
    - '#c2c3c6'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.8542014788836241
  rhythmicContrast: 0
purpose: []
