color:
  brandStrength: 0.4375
  saturation: 0.8542014788836241
  brandColors:
    - '#252528'
    - '#5d6671'
    - '#feffff'
    - '#8895a7'
    - '#c2c3c6'
  lightness: 0.4786434546113014
  rhythmicContrast: 0.03659296478144825
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
favicon: null
layout_spectrum: 0.3127290129195899
purpose: []
name: Incentive Pictures
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8579761078581214
