name: The Way Down
favicon: null
layout_spectrum: 0.3127290129195899
typography_spectrum: 0.8579761078581214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3477419796399772
  lightness: 0.4786434546113014
  saturation: 0.8542014788836241
  rhythmicContrast: 0.036592964781448245
purpose: []
