name: The Way Down
favicon: null
layout_spectrum: 0.3127290129195899
typography_spectrum: 0.8579761078581214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8592a4'
    - '#101115'
    - '#5c6063'
    - '#6d7987'
    - '#383c3f'
  brandStrength: 0.4375
  lightness: 0.4786434546113014
  saturation: 0.8542014788836241
  rhythmicContrast: 0.036592964781448245
purpose: []
